export { 
  createAnnualInterestRate,
  MIN_ALLOWED_INTEREST_RATE,
  MAX_ALLOWED_INTEREST_RATE,
  DESCRIPTION_MIN_ALLOWED_INTEREST_RATE,
  DESCRIPTION_MAX_ALLOWED_INTEREST_RATE
} from "./annualInterestRate.factory";